initial.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,12 +5,18 @@
 
 source common.inc
 
+timestamp=$(date --rfc-3339=seconds | sed 's/ /_/')
 for folder in work/openssl*/; do
-	echo "${banner} building in ${folder}"
-	cd ${folder}
-	./config || fail "configure failed"
-	make -j4 || fail "compilation failed"
-	cd -
-	echo "${banner} done with ${folder}"
+	echo -ne "${banner} building in ${folder}"
+	time (	
+		cd ${folder}
+		gcc -v
+		[[ -f ./Configure ]] && ./Configure
+		./config 	|| echo "configure failed"
+		make -j$(nproc)	|| echo "compilation failed"
+	) &> ${folder}/buildlog-${timestamp}.log \
+	  || fail "compilation of ${folder} failed"
+	wait
+	echo -e "\t\t$(tput bold)DONE$(tput sgr0)"
 done
 
diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,10 +1,7 @@
 #!/usr/bin/env bash
 #
-# Download and optionally build OpenSSL versions
-# for comparison, testing, fuzzing [...]
+# Download, build and compare OpenSSL versions for testing, fuzzing [...] 
 #
-
-#set -x
 
 source common.inc
 
@@ -55,17 +52,15 @@ if [ ! -d "work/" ]; then
 fi
 
 echo "${banner} downloading all OpenSSL sources - this might take a while"
-#wget -r -l2 -nd -Nc -A "*.tar.gz" -A "*.md5" -P "work/" \
-#	"https://www.openssl.org/source" &>/dev/null || fail "could not download OpenSSL"
+wget -r -l2 -nd -Nc -A "*.tar.gz" -A "*.md5" -P "work/" \
+	"https://www.openssl.org/source" &>/dev/null || fail "could not download OpenSSL"
 
 echo "${banner} verifying tarballs:"
-#verify_tarballs
+verify_tarballs
 
 echo "${banner} extracting tarballs:"
-#extract_tarballs
+extract_tarballs
 
-if [ ${build} ]; then
-	source build
-fi
+[[ ${build} ]] && source build
 
 echo "${banner} done."
